/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemType = IDL.Variant({
  'controller' : IDL.Null,
  'console' : IDL.Null,
  'game' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Pricing = IDL.Record({
  'controller' : IDL.Nat,
  'console' : IDL.Nat,
  'game' : IDL.Nat,
});
export const RentalInquiry = IDL.Record({
  'durationDays' : IDL.Nat,
  'totalCost' : IDL.Nat,
  'timestamp' : Time,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'startDate' : Time,
});

export const idlService = IDL.Service({
  'calculateRentalCost' : IDL.Func(
      [ItemType, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getPricing' : IDL.Func([], [Pricing], ['query']),
  'getRentalInquiries' : IDL.Func([], [IDL.Vec(RentalInquiry)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitRentalInquiry' : IDL.Func(
      [ItemType, IDL.Nat, Time, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updatePricing' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemType = IDL.Variant({
    'controller' : IDL.Null,
    'console' : IDL.Null,
    'game' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Pricing = IDL.Record({
    'controller' : IDL.Nat,
    'console' : IDL.Nat,
    'game' : IDL.Nat,
  });
  const RentalInquiry = IDL.Record({
    'durationDays' : IDL.Nat,
    'totalCost' : IDL.Nat,
    'timestamp' : Time,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'startDate' : Time,
  });
  
  return IDL.Service({
    'calculateRentalCost' : IDL.Func(
        [ItemType, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getPricing' : IDL.Func([], [Pricing], ['query']),
    'getRentalInquiries' : IDL.Func([], [IDL.Vec(RentalInquiry)], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitRentalInquiry' : IDL.Func(
        [ItemType, IDL.Nat, Time, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updatePricing' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };