/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type ItemType = { 'controller' : null } |
  { 'console' : null } |
  { 'game' : null };
export interface Pricing {
  'controller' : bigint,
  'console' : bigint,
  'game' : bigint,
}
export interface RentalInquiry {
  'durationDays' : bigint,
  'totalCost' : bigint,
  'timestamp' : Time,
  'itemType' : ItemType,
  'quantity' : bigint,
  'startDate' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'calculateRentalCost' : ActorMethod<[ItemType, bigint, bigint], bigint>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getPricing' : ActorMethod<[], Pricing>,
  'getRentalInquiries' : ActorMethod<[], Array<RentalInquiry>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'submitRentalInquiry' : ActorMethod<[ItemType, bigint, Time, bigint], bigint>,
  'updatePricing' : ActorMethod<[bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];